Repository wecode-bootcamp-korea/23-1st-ggugit-frontend, pull requests merged in 2021-08, with the labels that each got.

#2 [23기 김동우] [MODIFY] : nav, footer review 반영 및 conflict 예상 파일 정리
  public/index.html
  src/Routes.js
  src/component/Footer.js
  src/component/Footer.scss
  src/component/Footer/FOOTER_LIST.js
  src/component/Footer/Footer.js
  src/component/Footer/Footer.scss
  src/component/Nav.js
  src/component/Nav.scss
  src/component/Nav/NAV_LIST.js
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/pages/Login/1.txt
  src/styles/common.scss
  src/styles/reset.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#4 [23기 김동우 ] [MODIFY] : review suggestion 내용 반영
  src/Routes.js
  src/component/Form/CommonForm.js
  src/component/Form/CommonForm.scss
  src/component/Input/CommonInput.js
  src/component/Input/CommonInput.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm/LOGIN_INPUT_LIST.js
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/Login/LoginForm/LoginForm.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpForm/SIGN_UP_INPUT_LIST.js
  src/pages/SignUp/SignUpForm/SignUpForm.js
  src/pages/SignUp/SignUpForm/SignUpForm.scss
  src/styles/variables.scss
Labels: Status: Accepted

#6 [23기 김동우] [MODIFY] : nav style change
  src/component/Nav/NAV_LIST.js
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
Labels: Status: Accepted

#8 [23기 김동우] [MODIFY] : input key error fix
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/SignUp/SignUpForm/SignUpForm.js
Labels: Status: 리뷰 요청

#5 [23기 김동우] [ADD] login, signUp fetch logic 작성
  src/component/Form/CommonForm.js
  src/component/Form/CommonForm.scss
  src/component/Input/CommonInput.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/LoginForm/LOGIN_INPUT_LIST.js
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpForm/SIGN_UP_INPUT_LIST.js
  src/pages/SignUp/SignUpForm/SignUpForm.js
Labels: Status: 리뷰 요청

#9 [23기 이지선] [MODIFY] menu_layout 1차 수정
  public/index.html
  src/Routes.js
  src/pages/Menu/1.txt
  src/pages/Menu/List/List.js
  src/pages/Menu/List/List.scss
  src/pages/Menu/Menu.js
  src/pages/Menu/Menu.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#10 [23기 김동우] [FIX] : signUp style overlap
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 수정 요청

#7 [23기 황문실] [MODIFY] 상세페이지 레이아웃
  .swo
  .swp
  public/data/DetailPage/MockdData.json
  public/images/DetailPage/mainBoxImg.jpeg
  public/images/DetailPage/pasta_above.jpeg
  public/index.html
  src/Routes.js
  src/pages/DetailPage/1.txt
  src/pages/DetailPage/Components/ASIDE_BOTTOM_DATA.js
  src/pages/DetailPage/Components/CartButton.js
  src/pages/DetailPage/Components/CartButton.scss
  src/pages/DetailPage/Components/CartStickyBar.js
  src/pages/DetailPage/Components/CartStickyBar.scss
  src/pages/DetailPage/Components/DishData.js
  src/pages/DetailPage/Components/DishData.scss
  src/pages/DetailPage/Components/MainContent.js
  src/pages/DetailPage/Components/MainContent.scss
  src/pages/DetailPage/Components/TitleData.js
  src/pages/DetailPage/Components/TitleData.scss
  src/pages/DetailPage/Detail.js
  src/pages/DetailPage/Detail.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#11 [23기 김동우] [ADD] : main ImageSlider 구현 완료
  public/images/Main/food2.jpg
  public/images/Main/food3.jpg
  public/images/Main/stake.jpg
  public/index.html
  src/pages/Main/Asides/ImageSlider.js
  src/pages/Main/Asides/ImageSlider.scss
  src/pages/Main/Asides/ImageSliderButton/ImageSliderButton.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainImageSlider/MainImageSlider.js
  src/pages/Main/MainImageSlider/MainImageSlider.scss
Labels: Status: 리뷰 요청

#13 [ADD] : main tasteBlock, searchBar, onTimeBest 작성
  public/data/DetailPage/1.txt
  public/data/DetailPage/TitleMockData.json
  public/images/DetailPage/1.txt
  public/images/DetailPage/left.png
  public/images/DetailPage/right.png
  public/index.html
  src/Routes.js
  src/component/Footer/Footer.js
  src/component/Nav/NAV_LIST.js
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/config.js
  src/pages/DetailPage/Components/ASIDE_BOTTOM_DATA.js
  src/pages/DetailPage/Components/CartButton.js
  src/pages/DetailPage/Components/CartButton.scss
  src/pages/DetailPage/Components/CartStickyBar.js
  src/pages/DetailPage/Components/CartStickyBar.scss
  src/pages/DetailPage/Components/DishData.js
  src/pages/DetailPage/Components/DishData.scss
  src/pages/DetailPage/Components/MainContent.js
  src/pages/DetailPage/Components/MainContent.scss
  src/pages/DetailPage/Components/TitleData.js
  src/pages/DetailPage/Components/TitleData.scss
  src/pages/DetailPage/Detail.js
  src/pages/DetailPage/Detail.scss
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/Main/Asides/ImageSlider/ImageSlider.js
  src/pages/Main/Asides/ImageSlider/ImageSlider.scss
  src/pages/Main/Asides/OnTimeBest/OnTimeBest.js
  src/pages/Main/Asides/OnTimeBest/OnTimeBest.scss
  src/pages/Main/Asides/OnTimeBest/OnTimeBestImage.js
  src/pages/Main/Asides/OnTimeBest/OnTimeBestImage.scss
  src/pages/Main/Asides/RealImageRender/RealImageRender.js
  src/pages/Main/Asides/SearchBar/SearchBar.js
  src/pages/Main/Asides/SearchBar/SearchBar.scss
  src/pages/Main/Asides/TasteRecommend/TasteModal/TasteModal.js
  src/pages/Main/Asides/TasteRecommend/TasteModal/TasteModal.scss
  src/pages/Main/Asides/TasteRecommend/TasteRecommend.js
  src/pages/Main/Asides/TasteRecommend/TasteRecommend.scss
  src/pages/Main/Asides/Timer/Timer.js
  src/pages/Main/Asides/Timer/Timer.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainImageSlider/MainImageSlider.js
  src/pages/Main/MainImageSlider/MainImageSlider.scss
  src/pages/Menu/Menu.js
Labels: Status: 리뷰 요청

#12 [23기 이지선3577][ADD]menu logic 구현 완료
  public/data/Menu/data.json
  src/config/config.js
  src/pages/Menu/List/List.js
  src/pages/Menu/Menu.js
  src/pages/Menu/Menu.scss
  src/pages/Menu/MenuCategory/MenuCategory.js
  src/pages/Menu/MenuContainer/MenuContainer.js
  src/pages/Menu/MenuList/MENU_LIST.js
  src/pages/Menu/MenuList/MenuList.js
  src/pages/Menu/MenuList/MenuList.scss
Labels: Status: Accepted

#14 [23기 황문실] [MODIFY]상세페이지 logic 구현
  public/data/DetailPage/MockdData.json
  public/data/DetailPage/TitleMockData.json
  public/index.html
  src/Routes.js
  src/config.js
  src/pages/DetailPage/Aside/ASIDE_BOTTOM_DATA.js
  src/pages/DetailPage/Aside/CartButton.js
  src/pages/DetailPage/Aside/CartButton.scss
  src/pages/DetailPage/Aside/CartStickBar.js
  src/pages/DetailPage/Aside/CartStickBar.scss
  src/pages/DetailPage/Aside/DishData.js
  src/pages/DetailPage/Aside/DishData.scss
  src/pages/DetailPage/Aside/ImgAlbum.js
  src/pages/DetailPage/Aside/ImgAlbum.scss
  src/pages/DetailPage/Aside/MainContent.js
  src/pages/DetailPage/Aside/MainContent.scss
  src/pages/DetailPage/Aside/TitleData.js
  src/pages/DetailPage/Aside/TitleData.scss
  src/pages/DetailPage/Components/DishData.js
  src/pages/DetailPage/Components/MainContent.js
  src/pages/DetailPage/Components/MainContent.scss
  src/pages/DetailPage/Components/TitleData.js
  src/pages/DetailPage/Detail.js
  src/pages/DetailPage/Detail.scss
  src/styles/variables.scss
Labels: Status: Conflict 발생

#16 [23기 이지선][ADD]logic 수정사항 반영 commit
  src/config/config.js
  src/pages/Menu/Menu.js
  src/pages/Menu/MenuCategory/MenuCategory.js
  src/pages/Menu/MenuList/MenuList.js
Labels: Status: 수정 요청, Status: Conflict 발생

#21 Feature/cart
  public/index.html
  src/Routes.js
  src/component/Nav/NAV_LIST.js
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/pages/Cart/Asides/CartList.js
  src/pages/Cart/Asides/CartList.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/Main/Asides/ImageSlider/ImageSlider.js
  src/pages/Main/Asides/OnTimeBest/OnTimeBest.js
  src/pages/Main/Asides/OnTimeBest/OnTimeBestImage.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청
